steps:
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      docker build -t us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/ljf-test01-image:v1 .
    automapSubstitutions: true
images:
  - 'us-west2-docker.pkg.dev/omnitrack-test-359902/quickstart-docker-repo/ljf-test01-image:v1'
options:
  logging: CLOUD_LOGGING_ONLY